### ISSUE TITLE
package.json postinstall breaks the npm install

### ISSUE THREAD

**Issue by garyrusso** [marklogic/Geophoto#1]
package.json postinstall line causes the npm install to fail.

This is the error message.

$ npm install && bower install
npm WARN package.json Geophoto@0.0.1 No repository field.

> Geophoto@0.0.1 postinstall c:\projects\geophoto
> ./node_modules/bower/bin/bower install

'.' is not recognized as an internal or external command,
operable program or batch file.

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "c:\Program Files\nodejs\node.exe" "c:\Program Files\nodejs\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v0.12.0
npm ERR! npm  v2.5.1
npm ERR! code ELIFECYCLE
npm ERR! Geophoto@0.0.1 postinstall: `./node_modules/bower/bin/bower install`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the Geophoto@0.0.1 postinstall script './node_modules/bower/bin/bower install'.
npm ERR! This is most likely a problem with the Geophoto package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./node_modules/bower/bin/bower install
npm ERR! You can get their info via:
npm ERR!     npm owner ls Geophoto
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     c:\projects\geophoto\npm-debug.log

**Comment by tpiros** [comment]
This problem occurs when setting up on a windows environment - the execution of the postinstall script fails. For the time being there are 2 solutions:

1) remove the postinstall line and do the bower installation manually, or,
2) if you have bower installed globally on your system, you can replace the postinstall line with 'bower install'

**Comment by tpiros** [comment]
Commit https://github.com/marklogic/Geophoto/commit/6562985988750315b11a8c53845d24a7cc012643(6562985) contains a potential fix for Windows environments
