### ISSUE TITLE
Refactor updateDocument to use patch

### ISSUE THREAD

**Issue by dmcassel** [marklogic/Geophoto#3]
The updateDocument function is used to update the title and description of an image. Currently, it reads the document, updates it locally, then writes the entire document back. This approach is because patch replaceInsert could not work with just a value at the time the function was written.

**Comment by tpiros** [comment]
Committed: [https://github.com/dmcassel/Geophoto/commit/b29397daa47a729875fb1358c14b661b7f8cfaf2](https://github.com/dmcassel/Geophoto/commit/b29397daa47a729875fb1358c14b661b7f8cfaf2)
